/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;

import userinterface.ManagerRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HouseKeepingOragnization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ManagerRequestTestJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Enterprise enterprise;
    private UserAccount userAccount;
    String studentname,email,phone, dob, allergy, foodPref, respRate, heartRate, bloodP, weight;
    WorkRequest wr;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public ManagerRequestTestJPanel(JPanel container, UserAccount account, Enterprise enterprise,WorkRequest wr,String studentname,String email,String phone,String dob,String allergy,String foodPref,String respRate,String heartRate,String bloodP,String weight) {
        initComponents();
        
        this.wr = wr;
        this.studentname = studentname;
        this.container = container;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.email=email;
        this.phone=phone;
        this.dob=dob;
        this.allergy=allergy;
        this.foodPref=foodPref;
        this.respRate=respRate;
        this.heartRate=heartRate;
        this.bloodP=bloodP;
        this.weight=weight;
        
        //valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(0, 51, 255));
        requestTestJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setText("REQUEST HOUSEKEEPING FOR SERVICES");
        requestTestJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 370, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("RESULT MESSAGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 320, 110));

        backJButton.setBackground(new java.awt.Color(0, 51, 255));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("BACK");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 90, 60));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 630, 410));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("MANAGER ORGANIZATION :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 300, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        String message = messageJTextField.getText();
        
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setStudentName(studentname);
        //email,phone, dob, allergy, foodPref, respRate, heartRate, bloodP, weight;
        request.setEmailId(email);
        request.setPhoneNum(phone);
        request.setDOB(dob);
        request.setAllergies(allergy);
        request.setFoodPref(foodPref);
        request.setRespRate(respRate);
        request.setHeartRate(heartRate);
        request.setBloodPressure(bloodP);
        request.setWeight(weight);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HouseKeepingOragnization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        if(messageJTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter a message", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(null, "Requested Successfully", "INFORMATION",JOptionPane.INFORMATION_MESSAGE);
        messageJTextField.setText("");
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagerWorkAreaJPanel dwjp = (ManagerWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestTestJButton;
    // End of variables declaration//GEN-END:variables
}
